<?php

/**
 * @file
 * Contains opigno_course.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
//use Drupal\opigno_learning_path\Database\LearningPathContentsDatabase;
//use Drupal\opigno_learning_path\LearningPathToolsManager;

/**
 * Implements hook_help().
 */
function opigno_course_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opigno_course module.
    case 'help.page.opigno_course':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds course feature to your Opigno instance.') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_form_alter().
 */
function opigno_course_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $destination = \Drupal::request()->get('destination', FALSE);
  if ($destination === FALSE || substr($destination, -14) != 'course-content') {
    return;
  }

  $destination_parts = explode('/', $destination);
  $destination_id = $destination_parts[3];
  if (!is_numeric($destination_id)) {
    return;
  }

//  $tools_manager = new LearningPathToolsManager();
//  $tools = $tools_manager->getTools();
//  foreach($tools as $tool) {
//    if ($tool->getCreateFormId() == $form_id || $tool->getEditFormId() == $form_id) {
//      // Add the course ID to the form.
//      $form['opigno_course_course_id'] = [
//        '#type' => 'hidden',
//        '#value' => $destination_id
//      ];
//
//      $form['opigno_course_tool_entity_type'] = [
//        '#type' => 'hidden',
//        '#value' => $tool->getToolEntityType()
//      ];
//
//      $form['opigno_course_tool_entity_bundle'] = [
//        '#type' => 'hidden',
//        '#value' => $tool->getToolEntityBundle()
//      ];
//
//      // Handle the submit, so we can link the new entity with the course.
//      foreach (array_keys($form['actions']) as $action) {
//        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
//          $form['actions'][$action]['#submit'][] = 'opigno_course_linked_content_form_submit';
//        }
//      }
//    }
//  }
}

//function opigno_course_linked_content_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
//  $content_nid = $form_state->getValue('nid');
//  $course_id = $form_state->getValue('opigno_course_course_id');
//  $content_type = $form_state->getValue('opigno_course_tool_entity_type');
//  $content_bundle = $form_state->getValue('opigno_course_tool_entity_bundle');
//
//  $db = new LearningPathContentsDatabase(\Drupal::getContainer()->get('database'));
//  $db->addContent($course_id, $content_type, $content_bundle, $content_nid);
//}
