<?php

/**
 * @file
 * Module functionality implementation.
 */

/**
 * Implements hook_field_widget_info_alter().
 */
function opigno_scorm_field_widget_info_alter(array &$info) {
  $info['file_generic']['field_types'][] = 'opigno_scorm_package';
}

/**
 * Implements hook_theme().
 */
function opigno_scorm_theme() {
  return [
    'opigno_scorm__player' => [
      'variables' => ['scorm_id' => NULL, 'tree' => [], 'start_sco' => NULL],
      'template' => 'opigno-scorm--player',
    ],
    'opigno_scorm__player_tree' => [
      'variables' => ['tree' => []],
      'template' => 'opigno-scorm--player-tree',
    ],
    'opigno_scorm__player_tree_item' => [
      'variables' => ['sco' => NULL],
      'template' => 'opigno-scorm--player-tree-item',
    ],
  ];
}

/**
 * Get the available CMI paths for the SCORM player.
 *
 * Invokes the hook_opigno_scorm_register_cmi_paths() on all implementing modules
 * to retrieve data to pass to the SCORM player.
 *
 * @return array
 */
function opigno_scorm_add_cmi_paths($scorm_version) {
  $paths = \Drupal::moduleHandler()->invokeAll('opigno_scorm_register_cmi_paths', [$scorm_version]);
  \Drupal::moduleHandler()->alter('opigno_scorm_register_cmi_paths', $paths);
  return $paths;
}

/**
 * Get the CMI data for the SCORM player.
 *
 * Invokes the hook_opigno_scorm_ui_register_cmi_data() on all implementing modules
 * to retrieve data to pass to the SCORM player.
 *
 * @param object $scorm
 * @param array $scos
 *
 * @return array
 */
function opigno_scorm_add_cmi_data($scorm, $scos, $scorm_version) {
  $data = \Drupal::moduleHandler()->invokeAll('opigno_scorm_register_cmi_data', [$scorm, $scos, $scorm_version]);
  \Drupal::moduleHandler()->alter('opigno_scorm_register_cmi_data', $data, $scorm, $scos);
  return $data;
}

/**
 * Implements hook_opigno_scorm_register_cmi_paths().
 */
function opigno_scorm_opigno_scorm_register_cmi_paths($scorm_version) {
  switch ($scorm_version) {
    case '2004':
      $data = array(
        'cmi.location' => array(),
        'cmi.completion_status' => array(),
        'cmi.exit' => array(),
        'cmi.learner_id' => array(),
        'cmi.learner_name' => array(),
        'cmi.learner_preference._children' => array(),
        'cmi.learner_preference.audio_level' => array(),
        'cmi.learner_preference.language' => array(),
        'cmi.learner_preference.delivery_speed' => array(),
        'cmi.learner_preference.audio_captioning' => array(),
      );
      break;

    case '1.2':
      $data = array(
        'cmi.core.lesson_location' => array(),
        'cmi.core.lesson_status' => array(),
        'cmi.core.exit' => array(),
        'cmi.core.student_name' => array(),
        'cmi.core.student_id' => array(),
        'cmi.student_preference._children' => array(),
        'cmi.student_preference.audio' => array(),
        'cmi.student_preference.language' => array(),
        'cmi.student_preference.speed' => array(),
        'cmi.student_preference.text' => array(),
        'cmi.core.score._children' => array(),
      );
      break;
  }
  return $data;
}

/**
 * Implements hook_opigno_scorm_register_cmi_data().
 */
function opigno_scorm_opigno_scorm_register_cmi_data($scorm, $scos, $scorm_version) {
  $account = \Drupal::currentUser();

  if (!$account->id()) {
    $learner_name = "anonymous";
  }
  else {
    $learner_name = $account->getAccountName();
  }

  switch ($scorm_version) {
    case '2004':
      $data = array(
        'cmi.location' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.location', ''),
        'cmi.completion_status' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.completion_status', 'unknown'),
        'cmi.exit' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.exit', ''),
        'cmi.learner_id' => $account->id(),
        'cmi.learner_name' => $learner_name,
        'cmi.learner_preference._children' => "audio_level,language,delivery_speed,audio_captioning",
        'cmi.learner_preference.audio_level' => 1,
        'cmi.learner_preference.language' => '',
        'cmi.learner_preference.delivery_speed' => 1,
        'cmi.learner_preference.audio_captioning' => 0,
      );
      break;

    case '1.2':
      $data = array(
        'cmi.core.lesson_location' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.lesson_location', ''),
        'cmi.core.exit' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.exit', ''),
        'cmi.core.student_id' => $account->id(),
        'cmi.core.student_name' => $learner_name,
        'cmi.student_preference._children' => "audio,language,speed,text",
        'cmi.student_preference.audio' => array(),
        'cmi.student_preference.language' => array(),
        'cmi.student_preference.speed' => array(),
        'cmi.student_preference.text' => array(),
        'cmi.core.score._children' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score._children', 'raw,min,max'),
      );
      break;
  }

  return $data;
}

/**
 * Helper function to get SCORM CMI data while also providing a default value.
 *
 * @param int $uid
 * @param int $scorm_id
 * @param string $cmi_key
 * @param mixed $default_value
 *
 * @return mixed|null
 */
function opigno_scorm_scorm_cmi_get($uid, $scorm_id, $cmi_key, $default_value = NULL) {
  $value = opigno_scorm_cmi_get($uid, $scorm_id, $cmi_key);
  return isset($value) ? $value : $default_value;
}

/**
 * Get a CMI data value for the given SCORM.
 *
 * @param int $uid
 * @param int $scorm_id
 * @param string $cmi_key
 *
 * @return mixed|null
 */
function opigno_scorm_cmi_get($uid, $scorm_id, $cmi_key) {
  $data = NULL;
  $result = db_select('opigno_scorm_scorm_cmi_data', 'o')
    ->fields('o', array('value', 'serialized'))
    ->condition('o.uid', $uid)
    ->condition('o.scorm_id', $scorm_id)
    ->condition('o.cmi_key', $cmi_key)
    ->execute()
    ->fetchObject();

  if (isset($result->value)) {
    $data = !empty($result->serialized) ? unserialize($result->value) : $result->value;
  }

  return $data;
}

/**
 * Set a CMI data value for the given SCORM.
 *
 * @param int $uid
 * @param int $scorm_id
 * @param string $cmi_key
 * @param string $value
 *
 * @return bool
 */
function opigno_scorm_scorm_cmi_set($uid, $scorm_id, $cmi_key, $value) {
  if (isset($value)) {
    $serialized = 0;
    if (is_array($value) || is_object($value)) {
      $value = serialize($value);
      $serialized = 1;
    }
    elseif (is_bool($value)) {
      $value = (int) $value;
    }

    $result = db_merge('opigno_scorm_scorm_cmi_data')
      ->keys([
        'uid' => $uid,
        'scorm_id' => $scorm_id,
        'cmi_key' => $cmi_key,
      ])
      ->fields([
        'uid' => $uid,
        'scorm_id' => $scorm_id,
        'cmi_key' => $cmi_key,
        'value' => $value,
        'serialized' => $serialized,
      ])
      ->execute();

    return !!$result;
  }
  else {
    return TRUE;
  }
}

/**
 * Implements hook_opigno_scorm_commit().
 */
function opigno_scorm_opigno_scorm_commit($scorm, $sco_id, $data) {
  $account = Drupal::currentUser();

  if (!empty($data->scorm_version)) {
    switch ($data->scorm_version) {
      case '2004':
        // Store the last visited SCO id.
        opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'user.sco', $sco_id);

        // Store the last position.
        if (!empty($data->cmi->location)) {
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.location', $data->cmi->location);
        }

        // Store suspend data value.
        if (!empty($data->cmi->suspend_data)) {
          if (!is_null($sco_id)) {
            opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.suspend_data.' . $sco_id, $data->cmi->suspend_data);
          }
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.suspend_data', $data->cmi->suspend_data);
        }

        // Store the completion status.
        if (!empty($data->cmi->completion_status)) {
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.completion_status', $data->cmi->completion_status);
        }
        break;

      case '1.2':
        // Store the last position.
        if (!empty($data->cmi->core->lesson_location)) {
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.core.lesson_location', $data->cmi->core->lesson_location);
        }

        // Store suspend data value.
        if (!empty($data->cmi->suspend_data)) {
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.suspend_data', $data->cmi->suspend_data);
        }

        // Store the completion status.
        if (!empty($data->cmi->core->lesson_status)) {
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.core.lesson_status', $data->cmi->core->lesson_status);
        }
        break;
    }
  }
}
