<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function opigno_h5p_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'opigno_answer_opigno_h5p_form') {
    $form['actions']['submit']['#submit'][] = '_opigno_h5_form_submit';
  }
}

/**
 * Form submit callback, used in opigno_h5p_form_alter().
 *
 * Saves user answer & correct answer patterns.
 */
function _opigno_h5_form_submit($form, FormStateInterface $form_state) {
  $correct_response = $form_state->getValue('correct-response');
  $response = $form_state->getValue('response');

  /** @var \Drupal\opigno_module\Form\OpignoAnswerForm $form_obj */
  $form_obj = $form_state->getFormObject();
  /** @var \Drupal\opigno_module\Entity\OpignoAnswer $entity */
  $answer = $form_obj->getEntity();

  $answer->set('field_correct_response', $correct_response);
  $answer->set('field_response', $response);

  $answer->save();
}
