<?php

/**
 * @file
 * Module main functionality.
 */

/**
 * Implements hook_opigno_scorm_register_cmi_paths().
 */
function opigno_scorm_activity_opigno_scorm_register_cmi_paths($scorm_version) {
  switch ($scorm_version) {
    case '2004':
      $data = array(
        'cmi.score.raw' => array(),
        'cmi.score.min' => array(),
        'cmi.score.max' => array(),
        'cmi.score.scaled' => array(),
        'cmi.suspend_data' => array(),
        'cmi.success_status' => array(),
        'cmi.objectives' => array(),
        'cmi.objectives._count' => array('readOnly' => 1),
        'cmi.objectives._children' => array('readOnly' => 1),
        'cmi.objectives.n.id' => array(),
        'cmi.objectives.n.score' => array(),
        'cmi.objectives.n.score._children' => array('readOnly' => 1),
        'cmi.objectives.n.score.scaled' => array(),
        'cmi.objectives.n.score.raw' => array(),
        'cmi.objectives.n.score.min' => array(),
        'cmi.objectives.n.score.max' => array(),
        'cmi.objectives.n.success_status' => array(),
        'cmi.objectives.n.completion_status' => array(),
        'cmi.objectives.n.progress_measure' => array(),
        'cmi.objectives.n.description' => array(),
      );
      break;

    case '1.2':
      $data = array(
        'cmi.core.score.raw' => array(),
        'cmi.core.score.max' => array(),
        'cmi.core.score.min' => array(),
        'cmi.suspend_data' => array(),
        'cmi.core.lesson_status' => array(),
        'cmi.objectives' => array(),
        'cmi.objectives._count' => array('readOnly' => 1),
        'cmi.objectives._children' => array('readOnly' => 1),
        'cmi.objectives.n.id' => array(),
        'cmi.objectives.n.score' => array(),
        'cmi.objectives.n.score._children' => array('readOnly' => 1),
        'cmi.objectives.n.score.raw' => array(),
        'cmi.objectives.n.score.min' => array(),
        'cmi.objectives.n.score.max' => array(),
        'cmi.objectives.n.status' => array(),
      );
      break;
  }
  return $data;
}

/**
 * Implements hook_opigno_scorm_register_cmi_data().
 */
function opigno_scorm_activity_opigno_scorm_register_cmi_data($scorm, $scos, $scorm_version) {
  $account = \Drupal::currentUser();

  switch ($scorm_version) {
    case '2004':
      $data = array(
        'cmi.score.raw' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.raw', ''),
        'cmi.score.min' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.min', ''),
        'cmi.score.max' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.max', ''),
        'cmi.score.scaled' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.scaled', ''),
        'cmi.success_status' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.success_status', ''),
        'cmi.objectives' => array(),
      );
      // Get last visited SCO.
      $last_sco = opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'user.sco', '');
      if ($last_sco != '') {
        $data['cmi.suspend_data'] = opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.suspend_data.' . $last_sco, '');
      }
      else {
        $data['cmi.suspend_data'] = opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.suspend_data', '');
      }
      break;

    case '1.2':
      $data = array(
        'cmi.core.score.raw' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score.raw', ''),
        'cmi.core.score.min' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score.min', ''),
        'cmi.core.score.max' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score.max', ''),
        'cmi.core.lesson_status' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.lesson_status', ''),
        'cmi.suspend_data' => opigno_scorm_scorm_cmi_get($account->id(), $scorm->id, 'cmi.suspend_data', ''),
        'cmi.objectives' => array(),
      );
      break;
  }

  // Fetch the objectives.
  foreach ($scos as $sco) {
    if (!empty($sco->attributes['objectives'])) {
      foreach ($sco->attributes['objectives'] as $objective) {
        $stored_objective = opigno_scorm_activity_load_objective($account->id(), $scorm->id, $objective['id']);
        if ($scorm_version == '2004') {
          $defaults = array(
            'id' => $objective['id'],
            'score' => array(
              'scaled' => 0,
              'raw' => 0,
              'min' => 0,
              'max' => 0,
            ),
            'success_status' => '',
            'completion_status' => '',
            'progress_measure' => '',
            'description' => '',
          );
        }
        else {
          $defaults = array(
            'id' => $objective['id'],
            'score' => array(
              'raw' => 0,
              'min' => 0,
              'max' => 0,
            ),
            'status' => '',
          );
        }

        if (!empty($stored_objective)) {
          $stored_objective = (array) $stored_objective;
          $stored_objective += $defaults;
        }
        else {
          $stored_objective = $defaults;
        }

        $data['cmi.objectives'][] = $stored_objective;
      }
    }
  }

  return $data;
}

/**
 * Load all objective data for the given SCORM.
 *
 * Helper function to load objective CMI data that was stored. Pass the ID
 * of the objective to fetch the data for it.
 *
 * @param int $uid
 * @param int $scorm_id
 * @param string $objective_id
 *
 * @return object|null
 */
function opigno_scorm_activity_load_objective($uid, $scorm_id, $objective_id) {
  $objectives = &drupal_static(__FUNCTION__);

  if (!isset($objectives)) {
    // We query the database ourselves here instead of relying on opigno_scorm_scorm_cmi_get(),
    // as we need a LIKE query.
    $result = db_select('opigno_scorm_scorm_cmi_data', 'o')
      ->fields('o')
      ->condition('o.uid', $uid)
      ->condition('o.scorm_id', $scorm_id)
      ->condition('o.cmi_key', 'cmi.objectives.%', 'LIKE')
      ->execute();

    while ($row = $result->fetchObject()) {
      // Make sure this is one of ours.
      if (preg_match('/^cmi\.objectives\.[0-9]+$/', $row->cmi_key)) {
        $data = unserialize($row->value);

        // Allow modules to alter the data.
        $context = array(
          'uid' => $uid,
          'scorm_id' => $scorm_id,
          'original_value' => $data,
        );

        $objectives[$data->id] = $data;
      }
    }
  }

  return isset($objectives[$objective_id]) ? $objectives[$objective_id] : NULL;
}

/**
 * Implements hook_opigno_scorm_commit().
 */
function opigno_scorm_activity_opigno_scorm_commit($scorm, $sco_id, $data) {
  $account = Drupal::currentUser();

  // Store objectives and results.
  if (!empty($data->cmi->objectives)) {
    for ($i = 0, $len = count($data->cmi->objectives); $i < $len; $i++) {
      opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, "cmi.objectives.$i", $data->cmi->objectives[$i]);
    }
  }

  if (!empty($data->scorm_version)) {
    switch ($data->scorm_version) {
      case '2004':
        // Store the score.
        if (!empty($data->cmi->score)) {
          foreach (array('raw', 'min', 'max', 'scaled') as $key) {
            if (isset($data->cmi->score->{$key})) {
              opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, "cmi.score.{$key}", $data->cmi->score->{$key});
            }
          }
        }

        // Store the success status.
        if (!empty($data->cmi->success_status)) {
          opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, 'cmi.success_status', $data->cmi->success_status);
        }
        break;

      case '1.2':
        // Store the score.
        if (!empty($data->cmi->core->score)) {
          foreach (array('raw', 'min', 'max') as $key) {
            if (isset($data->cmi->core->score->{$key})) {
              opigno_scorm_scorm_cmi_set($account->id(), $scorm->id, "cmi.core.score.{$key}", $data->cmi->core->score->{$key});
            }
          }
        }
        break;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function opigno_scorm_activity_preprocess_opigno_scorm__player(&$variables) {
  $variables['#attached']['library'][] = 'opigno_scorm_activity/opigno_scorm_activity.main';
}
