<?php

/**
 * @file
 * Contains wind.module
 */

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_login().
 *
 * @param $account
 */
function wind_user_login($account) {
  $account_roles = $account->getRoles();
  if(in_array('learner', $account_roles)){
    $response = new RedirectResponse('course');
    $response->send();
  }

  if(in_array('user_manager', $account_roles)){
    $response = new RedirectResponse('manager');
    $response->send();
  }
}