<?php

/**
 * @file
 * Contains opigno_class.module.
 */

use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function opigno_class_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opigno_class module.
    case 'help.page.opigno_class':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds the classes to your Opigno instance. Works well with Opigno Learning Path.') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function opigno_class_preprocess_page(&$variables) {
  $route = \Drupal::routeMatch();
  $route_name = $route->getRouteName();

  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = $route->getParameter('group');
  if ($group === NULL || $group->bundle() !== 'opigno_class') {
    return;
  }

  if ($route_name === 'entity.group.canonical') {
    $user = \Drupal::currentUser();
    if ($user->hasPermission('manage group members in any group')
      || $group->hasPermission('administer members', $user)) {
      // If user can manage group members, add link to the members overview.
      $url = Url::fromRoute('opigno_learning_path.membership.overview', [
        'group' => $group->id(),
      ]);
      $link = Link::fromTextAndUrl(t('Manage members'), $url)->toRenderable();
      array_unshift($variables['page']['content'], $link);
    }
  }
  elseif ($route_name === 'entity.group.edit_form' && !$group->isNew()) {
    $url = Url::fromRoute('opigno_learning_path.membership.overview', [
      'group' => $group->id(),
    ]);
    $link = Link::fromTextAndUrl(t('Manage members'), $url)->toRenderable();
    array_unshift($variables['page']['content'], $link);
  }
}
